feat: add auth config for sas9 in target
sasjs/utils pull request #92
Opened 2021-07-01 10:33 UTC by sabhas

## Intent

intention is to add authconfig for sas9 server type
add encoding decoding utility

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] All unit tests are passing (`npm test`).
- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- [ ] Reviewer is assigned.

2021-07-01 11:41 UTC, allanbowe commented on src/utils/base64.spec.ts
> +  it('should return a base64 encoded string with encoded as prefix', () => {
Can we have a longer prefix - perhaps 100 characters?

2021-07-01 11:57 UTC, YuryShkoda requested changes

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/config.ts
> +export interface AuthConfigForSas9 {
pls rename it to `AuthConfigSAS9 `

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/target.spec.ts
> +    expect(target.authConfigForSas9).toEqual(authConfigForSas9)
you only need this assertion

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/target.spec.ts
> +  //224,234,246,256,266,277,285
please remove unnecessary comments

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/target.spec.ts
> +  it('should convert to JSON with authConfig is equal to this.authConfig', () => {
please clarify the purpose of this test case

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/targetValidators.ts
> +export const validateAuthConfigForSas9 = (
please rename it to `validateAuthConfigSAS9 `

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/targetValidators.ts
> +export const validateAuthConfigForSas9 = (
and you should also validate that `userName` and `password` are not empty strings

2021-07-01 11:57 UTC, YuryShkoda commented on src/utils/base64.spec.ts
> +  it('should return a base64 encoded string with encoded as prefix', () => {
I would create a variable for a test string

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/targetValidators.spec.ts
> +      expect(
you should create a variable for the config

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/targetValidators.spec.ts
> +  describe('For SAS(', () => {
delete `(`

2021-07-01 11:57 UTC, YuryShkoda commented on src/types/targetValidators.spec.ts
> +    it('should return the auth config for sas9 when valid', () => {
you should create a variable for the config

2021-07-01 16:55 UTC, sabhas commented
![Screenshot from 2021-07-01 21-52-10](https://user-images.githubusercontent.com/82647447/124161631-13251600-dab7-11eb-82d6-7c0ca9aa8f98.png)

2021-07-02 10:09 UTC, VladislavParhomchik approved these changes

2021-07-02 10:10 UTC, allanbowe approved these changes

2021-07-02 10:11 UTC, merged